## Numpy

Импортировать NumPy под именем np

In [3]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Создать вектор размера 10, заполненный единицами

In [7]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Создать вектор размера 10, заполненный числом 2.5

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [12]:
ZeroArr = np.zeros(10, dtype=int)
ZeroArr[4] = 1
print(ZeroArr)

[0 0 0 0 1 0 0 0 0 0]


Развернуть вектор (первый становится последним)

In [121]:
Arr = np.arange(0, 10, 1)
print(Arr)
#Arr = Arr[::-1]
Arr = np.flip(Arr,-1)
print(Arr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [96]:
np.arange(0, 9, 1).reshape((3, 3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [95]:
Arr =  np.array([1,2,0,0,4,0])
np.nonzero(Arr)

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [93]:
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Создать массив 3x3x3 со случайными значениями

In [92]:
np.random.random(size=(3, 3, 3))

array([[[0.94748341, 0.19960447, 0.73764486],
        [0.64565233, 0.11823327, 0.23854763],
        [0.83234618, 0.62477725, 0.65880629]],

       [[0.45174576, 0.50614012, 0.69486388],
        [0.39957941, 0.90244809, 0.90792311],
        [0.50130502, 0.42219251, 0.71185804]],

       [[0.86105351, 0.38752123, 0.43666626],
        [0.1814438 , 0.23486025, 0.35038563],
        [0.91092673, 0.76092285, 0.33819652]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [161]:
Arr = np.random.random(size=(30, 30))
#print(Arr)
np.mean(Arr)

0.49943045669815994

Перемножить матрицы 5x3 и 3x2

In [160]:
M1 = np.random.random(size=(5, 3))
M2 = np.random.random(size=(3, 2))
#print(M1 @ M2)
print(np.dot(M1, M2))

[[1.29783055 0.92599146]
 [1.19336439 0.70088619]
 [1.06234257 0.73613075]
 [1.01407542 0.85441219]
 [1.19558053 0.93101853]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [159]:
np.linspace(0, 1, 12, endpoint=True)[1:11]
#np.linspace(0, 1, 12, endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [193]:
Arr = np.random.random(size=20)
#print(Arr)
#print(np.max(Arr))
#print(np.argmax(Arr))
Arr[Arr.argmax()] = 0
#print(Arr)

Преобразовать массив из float в int

In [207]:
Arr = np.arange(20, dtype=np.float32)
#print(Arr)
Arr = Arr.astype(np.int32, copy=False)
#print(Arr)

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [334]:
import scipy.spatial

Arr = np.random.random((10,2))
Dist = scipy.spatial.distance.cdist(Arr,Arr)
#print(Dist)

Случайно расположить p элементов в 2D массив

In [329]:
n = 10
p = 10
Arr = np.zeros((n,n))
np.put(Arr, np.random.choice(range(n*n), p, replace=False), p)
#print(Arr)

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [206]:
Arr = np.array([1, 2, 3, 4, 5])
spaceZ = 3
ArrSpaced = np.zeros(len(Arr)+(len(Arr)-1)*spaceZ)
ArrSpaced[::spaceZ+1] = Arr
#print(ArrSpaced)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [308]:
Arr = np.random.randint(0, 100, 100)
#print(np.sort(Arr))
print(np.bincount(Arr).argmax())

4


Найти n наибольших значений в массиве

In [302]:
Arr = np.random.randint(0, 100, 20)
#print(Arr)
n = 3
print(Arr[np.argpartition(-Arr,n)[:n]])

[95 57 40 18 65 84 43 26  3 16 27  6  0 88  6 76 66 26 78 83]
[84 95 88]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [2]:
import pandas as pd
DF_products = pd.read_csv('en.openfoodfacts.org.products.tsv', sep='\t', header=0, low_memory=False)

Посмотреть первые 5 записей

In [3]:
#DF_products[:5]
DF_products.head(5)

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [30]:
#DF_products.count()
len(DF_products['code'])

356027

Сколько столбцов в наборе данных?

In [5]:
len(DF_products.columns)

163

Напечатайте все названия столбцов

In [6]:
DF_products.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [7]:
DF_products.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [8]:
DF_products.dtypes[104]

dtype('float64')

Как проиндексирован набор данных?

In [9]:
DF_products.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [10]:
DF_products.loc[19, ['product_name']]

product_name    Organic Oat Groats
Name: 19, dtype: object

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [1]:
import pandas as pd

chipo = pd.read_csv('chipotle.tsv', sep='\t', header=0, )
chipo['item_price'] = chipo['item_price'].str.replace('$', '')
chipo['order_id'] = pd.to_numeric(chipo['order_id'], errors='coerce')
chipo['quantity'] = pd.to_numeric(chipo['quantity'], errors='coerce')
chipo['item_price'] = pd.to_numeric(chipo['item_price'], errors='coerce')
#chipo.reindex(columns=['order_id', 'quantity', 'item_cost'])
chipo.head(5)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98

Как много продуктов стоят более чем $10.00?

In [2]:
#находим продукты с ценой более 10$
chipo['item_cost'] = chipo['item_price'] / chipo['quantity']  #создаем колонку 'item_cost' с ценой
chipo10 = chipo[chipo['item_cost'] > 10]  #сохраняем DF всех заказов-покупок продуктов с ценой более 10$
print(len(chipo10.groupby(['item_name'])['quantity'].sum()))

25


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [16]:
#группировка DF по продуктам дороже 10$ - выводим наименование, цену и суммарную стоимость
chipo10.groupby(['item_name', 'item_cost'])['item_price'].sum()

item_name              item_cost
Barbacoa Bowl          11.48          68.88
                       11.49          11.49
                       11.75         235.00
Barbacoa Burrito       11.08          11.08
                       11.48          11.48
                       11.75         258.50
Barbacoa Crispy Tacos  11.48          11.48
                       11.75          35.25
Barbacoa Salad Bowl    11.89          59.45
Barbacoa Soft Tacos    11.48          11.48
                       11.75          82.25
Carnitas Bowl          11.08          33.24
                       11.48          80.36
                       11.75         293.75
Carnitas Burrito       11.08          11.08
                       11.48          22.96
                       11.75         188.00
Carnitas Crispy Tacos  11.75          23.50
Carnitas Salad Bowl    11.89          47.56
Carnitas Soft Tacos    11.75          35.25
Chicken Bowl           10.58          10.58
                       10.98          32.94

Отсортировать по имени предмета

In [25]:
#сортировка DF с продуктами дороже 10$ по полю Наименование продукта
chipo10.set_index('item_name')
chipo10.sort_values(['item_name'], ascending=[True])

order_id  quantity          item_name  \
1175       483         1      Barbacoa Bowl   
2013       812         1      Barbacoa Bowl   
2073       836         1      Barbacoa Bowl   
4485      1786         1      Barbacoa Bowl   
471        202         1      Barbacoa Bowl   
4140      1657         1      Barbacoa Bowl   
1746       705         1      Barbacoa Bowl   
4046      1619         1      Barbacoa Bowl   
4510      1793         1      Barbacoa Bowl   
2749      1091         1      Barbacoa Bowl   
2762      1097         1      Barbacoa Bowl   
1643       664         1      Barbacoa Bowl   
4380      1748         1      Barbacoa Bowl   
136         61         1      Barbacoa Bowl   
919        380         1      Barbacoa Bowl   
3017      1200         1      Barbacoa Bowl   
4441      1770         1      Barbacoa Bowl   
1236       504         1      Barbacoa Bowl   
3025      1203         1      Barbacoa Bowl   
3394      1361         1      Barbacoa Bowl   
1174       483         1      Barbacoa Bowl   
58          27         1      Barbacoa Bowl   
1235       504         1      Barbacoa Bowl   
39          19         1      Barbacoa Bowl   
4594      1825         1      Barbacoa Bowl   
1383       562         1      Barbacoa Bowl   
3547      1426         1      Barbacoa Bowl   
4347      1736         1   Barbacoa Burrito   
450        195         1   Barbacoa Burrito   
375        163         1   Barbacoa Burrito   
...        ...       ...                ...   
2911      1157         1     Veggie Burrito   
3113      1243         1     Veggie Burrito   
3542      1424         1     Veggie Burrito   
3601      1443         3     Veggie Burrito   
4319      1723         1     Veggie Burrito   
479        205         1     Veggie Burrito   
225         99         1     Veggie Burrito   
973        400         1     Veggie Burrito   
931        384         1     Veggie Burrito   
3235      1294         1     Veggie Burrito   
1631       658         1     Veggie Burrito   
394        171         1     Veggie Burrito   
4471      1782         1     Veggie Burrito   
4278      1706         1     Veggie Burrito   
874        361         1     Veggie Burrito   
1695       687         1     Veggie Burrito   
1105       456         1     Veggie Burrito   
3404      1366         1     Veggie Burrito   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   

                                     choice_description  item_price  item_cost  
1175  [Fresh Tomato Salsa (Mild), [Black Beans, Rice...       11.48      11.48  
2013  [Tomatillo Red Chili Salsa, [Black Beans, Chee...       11.75      11.75  
2073  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...       11.75      11.75  
4485  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.75      11.75  
471   [[Tomatillo-Green Chili Salsa (Medium), Roaste...       11.48      11.48  
4140  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75      11.75  
1746  [Tomatillo Red Chili Salsa, [Cheese, Sour Crea...       11.75      11.75  
4046  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...       11.75      11.75  
4510                                        [Guacamole]       11.49      11.49  
2749  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.75      11.75  
2762  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...       11.75      11.75  
1643  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.75      11.75  
4380  [Fresh Tomato Salsa, [Fajita Veg

Сколько было заказано самого дорогого предмета?

In [15]:
chipo[(chipo['item_cost'] == chipo['item_cost'].max())]['quantity'].sum()

30

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [104]:
len(chipo[chipo['item_name'] =='Veggie Salad Bowl'])

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [107]:
len(chipo[(chipo['item_name'] =='Canned Soda') & (chipo['quantity'] > 1)])

20